project_id = "quwnagtoifzmbehwsoyc"

[functions.generate-script]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-narration]
verify_jwt = true

[functions.generate-music]
verify_jwt = true

[functions.generate-video]
verify_jwt = true

[functions.auto-movie]
verify_jwt = true
